name: download

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ffmpeg
          version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.13'
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Download
        run: bash download.sh
        env:
          QUERY_URL: ${{ secrets.QUERY_URL }}
      - name: Save Videos
        uses: actions/upload-artifact@v3
        with:
          name: output.mp4
          path: output.mp4